### ISSUE TITLE
Error During Journal Parse

### ISSUE THREAD

**Issue by lmosfa** [Silarn/EDMC-ExploData#1]
![Error_Journal_Parse](https://github.com/Silarn/EDMC-ExploData/assets/152731878/9a5a9948-f1ef-4808-a935-103993274f64)

Hi,
How do I submit a Report, please?

**Comment by Silarn** [comment]
Apologies, I just saw this issue. The most useful thing would be to upload the ExploData logs from the EDMC debug log file.

However, this does sometimes occur simply because the database was simply writing too much data and hit a lock timeout. If you can restart and have it continue processing then eventually it should finish. If, on the other hand, it continuously fails without making any progress then I will need to see the debug logs.

**Comment by denhal** [comment]
I am having the same issue. I installer edmc pioneer and edmc bioscan. I have attached a debug file for you.
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/16738482/EDMarketConnector-debug.log)

**Comment by Silarn** [comment]
Odd. I thought I set it up to skip up to 3 of these per journal file. I've seen this -nan(ind) issue before which is an invalid json value the game seems to rarely write under odd circumstances. The fact that that system has 0 bodies seems rather strange. It's probably a divide by 0 error when calculating the progress value.

I'm any case I'll have to see if I can forcibly replicate the issue and work around it.

**Comment by denhal** [comment]
I went into the attached Journal file and deleted that line and everything seems to works fine since.
Apala having no bodies is definitely a game error as it is a valid system in game with 23 bodies and many settlements and stations to dock at.

**Comment by Silarn** [comment]
It appears to be running the same line three times when the intent was to skip the problem line during the parse. I'll have to double check the logic there and make sure it skips the bad line.

**Comment by Silarn** [comment]
I believe b17616e will fix this, though I have not tested it just yet.

**Comment by Silarn** [comment]
I'm releasing this fix along with the latest version of BioScan. It will be pushed to Pioneer as well.
